{"timestamp": "2025-04-22T10:17:53.521815", "auth_service": {"type": "rest", "environment": "multi-cloud", "region": "asia-south", "instance_id": "auth-instance-9"}, "request": {"id": "req-9f6459d2a3ea4c7b", "method": "GET", "path": "/auth", "headers": {"Content-Type": "application/json", "Accept": "application/json", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/536.1 (KHTML, like Gecko) Chrome/46.0.878.0 Safari/536.1", "X-Request-ID": "req-9f6459d2a3ea4c7b"}, "body": {"username": "atharva"}, "client_id": "client-d955854d", "client_type": "browser", "source_ip": "149.97.246.93"}, "response": {"status_code": 500, "body": {"message": "auth request failed", "session_token": null}, "time_ms": 117.53}, "operation": {"type": "auth", "success": false, "user_id": "1e1e15bc-1cdc-4ad2-8e7d-569b845084e2", "tenant_id": "tenant-98"}, "security": {"mfa_used": false, "ip_reputation": "suspicious", "rate_limit": {"limit": 100, "remaining": 62, "reset": 1745320673}}, "tracing": {"correlation_id": "7388b817-96b2-4b10-80a1-02f7b4a819b3", "request_id": "req-9f6459d2a3ea4c7b", "previous_api": null, "session_id": "64dbf9db-557d-4ab2-806f-f42b8568386f"}, "is_anomalous": true, "error_info": "API returned error code 500. Possible spike in failures."}
